
const subjects = [
  ['Math AI', '∑', 'violet'], ['Science AI', '⌬', 'blue'], ['English AI', 'Aa', 'coral'],
  ['History & Social Studies', '⌘', 'gold'], ['Computer Science AI', '</>', 'green'],
  ['Languages', '◎', 'pink'], ['Arts', '✦', 'lavender'], ['Business', '↗', 'teal']
];

const icons = { home: '⌂', chat: '✦', library: '▤', images: '◫', school: '⌂', study: '◉', edit: '✎' };
let selectedSubjects = JSON.parse(localStorage.getItem('human-ai-subjects') || 'null') || ['Math AI', 'Science AI', 'English AI'];
let grade = localStorage.getItem('human-ai-grade') || '9th grade';
let page = 'school';
let mobileOpen = false;

function mark(s) { return selectedSubjects.includes(s) ? ' selected' : ''; }
function logo() { return `<div class="brand"><span class="logo">h</span><span>human <b>ai</b></span></div>`; }
function renderOnboarding() {
  const app = document.querySelector('#app');
  app.innerHTML = `<main class="onboarding"><section class="welcome-card">
    ${logo()}<div class="eyebrow">WELCOME TO YOUR LEARNING SPACE</div><h1>Let's make school<br><em>more human.</em></h1><p>Tell us a little about your school day so we can shape Human AI around the way you learn.</p>
    <div class="steps"><span class="active">1</span><i></i><span>2</span><i></i><span>3</span></div>
    <button class="primary wide" id="start">Set up my space <span>→</span></button>
  </section></main>`;
  document.querySelector('#start').onclick = renderSetup;
}
function renderSetup() {
  const app = document.querySelector('#app');
  app.innerHTML = `<main class="onboarding"><section class="setup-card">
    <button class="text-button" id="back">← Back</button>${logo()}<div class="eyebrow">YOUR LEARNING PROFILE</div>
    <h1>What grade are you in?</h1><p>This helps us make explanations that meet you where you are.</p>
    <div class="grade-grid">${['1st–3rd grade','4th–5th grade','6th–8th grade','9th grade','10th grade','11th grade','12th grade','College'].map(x => `<button class="grade ${x === grade ? 'picked':''}" data-grade="${x}">${x}</button>`).join('')}</div>
    <h2>What are you studying?</h2><p>Choose as many as you'd like. You can always change these later.</p>
    <div class="subject-picks">${subjects.map(([name, icon, color]) => `<button class="subject-pick${mark(name)}" data-subject="${name}"><span class="subject-icon ${color}">${icon}</span>${name}<b>✓</b></button>`).join('')}</div>
    <button class="primary wide" id="finish">Create my learning space <span>→</span></button>
  </section></main>`;
  document.querySelector('#back').onclick = renderOnboarding;
  document.querySelectorAll('.grade').forEach(el => el.onclick = () => { grade = el.dataset.grade; renderSetup(); });
  document.querySelectorAll('.subject-pick').forEach(el => el.onclick = () => { const n = el.dataset.subject; selectedSubjects = selectedSubjects.includes(n) ? selectedSubjects.filter(x=>x!==n) : [...selectedSubjects,n]; renderSetup(); });
  document.querySelector('#finish').onclick = () => { localStorage.setItem('human-ai-grade', grade); localStorage.setItem('human-ai-subjects', JSON.stringify(selectedSubjects)); localStorage.setItem('human-ai-onboarded','yes'); renderApp(); };
}
function sidebar() { return `<aside class="sidebar ${mobileOpen ? 'open':''}"><div class="sidebar-top">${logo()}<button class="close-mobile" aria-label="Close menu">×</button></div><button class="new-chat" data-page="chat"><span>＋</span> New chat <kbd>⌘ K</kbd></button><nav>
  <button data-page="chat"><span>${icons.chat}</span> Chat history</button><button data-page="library"><span>${icons.library}</span> Library</button><button data-page="images"><span>${icons.images}</span> Images</button>
  <div class="nav-label">LEARNING</div><button class="active" data-page="school"><span>${icons.school}</span> My school</button><button data-page="study"><span>${icons.study}</span> Study center</button><button data-page="editor"><span>${icons.edit}</span> Human editor</button>
  <div class="nav-label">MY SUBJECTS <button class="mini-add" data-page="subjects">+</button></div>${selectedSubjects.map(n => { const x=subjects.find(s=>s[0]===n); return `<button class="subject-nav" data-page="chat"><span class="subject-icon ${x[2]}">${x[1]}</span>${n}</button>`}).join('')}<button class="add-subject" data-page="subjects">＋ Add subject</button>
  </nav><div class="sidebar-bottom"><button class="avatar">JS <span><b>Jordan Smith</b><small>${grade}</small></span><i>⌄</i></button><button class="motion" id="motion">◌ <span>Reduce motion</span><i></i></button></div></aside>`; }
function header(title, sub) { return `<header class="page-header"><button class="menu" aria-label="Open menu">☰</button><div><div class="eyebrow">HUMAN AI / ${title.toUpperCase()}</div><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div><div class="header-actions"><button class="icon-button">⌕</button><button class="help">? <span>Help</span></button></div></header>`; }
function school() { return `${header('Good morning, Jordan', "Here's what your learning day looks like.")}<div class="content home"><section class="hero"><div><span class="pill">${grade} · Ridgeview High School</span><h2>Ready to make<br>today <em>yours?</em></h2><p>Pick up where you left off, get organized, or explore something new.</p><button class="primary" data-page="chat">Start a chat <span>→</span></button></div><div class="orbital"><span>✦</span><i>∑</i><b>⌬</b></div></section><section class="quick"><h3>Quick start</h3><div class="quick-grid"><button data-page="chat">✦ <b>Ask anything</b><small>Get help, learn, explore</small></button><button data-page="study">◉ <b>Study center</b><small>Prepare your way</small></button><button data-page="editor">✎ <b>Improve my writing</b><small>Keep your voice</small></button><button data-page="library">▤ <b>Open library</b><small>Find your files</small></button></div></section><div class="two-col"><section class="panel assignments"><div class="section-title"><h3>Coming up</h3><button>View calendar →</button></div><article><span class="date"><b>18</b>SEP</span><div><b>Algebra II · Problem Set 4</b><p>Due tomorrow · 12 problems</p></div><span class="tag violet-tag">Math</span></article><article><span class="date"><b>20</b>SEP</span><div><b>Biology · Cell Structure Lab</b><p>Due Friday · Lab report</p></div><span class="tag blue-tag">Science</span></article><article><span class="date"><b>23</b>SEP</span><div><b>English · The Odyssey response</b><p>Due Monday · 500 words</p></div><span class="tag coral-tag">English</span></article></section><section class="panel continue"><div class="section-title"><h3>Continue learning</h3><button>See all →</button></div><div class="continue-card"><span class="subject-icon violet">∑</span><div><small>MATH AI</small><b>Quadratic equations</b><p>Last activity · 15 min ago</p><div class="progress"><i></i></div></div><button>→</button></div></section></div></div>`; }
function chat() { return `${header('New chat', 'Your private space to think, ask, and learn.')}<main class="chat-page"><div class="chat-blank"><span class="big-logo">h</span><h2>What would you like to learn?</h2><p>Ask a question, upload a class file, or choose a subject to get started.</p><div class="prompt-chips"><button>Explain a tough concept</button><button>Help me study for a test</button><button>Brainstorm an idea</button></div></div><div class="composer"><button aria-label="Attach a file">＋</button><textarea aria-label="Message Human AI" placeholder="Message Human AI…"></textarea><button class="send" aria-label="Send message">↑</button><small>Human AI can make mistakes. Check important information.</small></div></main>`; }
function study() { const cards=[['▤','Study guides','Turn any topic into a clear, focused guide.'],['▦','Flashcards','Remember more with smart, spaced practice.'],['✓','Quizzes','Check what you know, without the pressure.'],['◉','Practice tests','Build confidence before the real thing.'],['↻','Review session','Revisit what matters most.']]; return `${header('Study center', 'Tools that help you understand, remember, and feel ready.')}<main class="content study"><section class="study-intro"><div><span class="pill">YOUR LEARNING TOOLKIT</span><h2>Study in a way that<br><em>works for you.</em></h2></div><p>Make every study session more focused, more personal, and a little less stressful.</p></section><div class="study-grid">${cards.map((c,i)=>`<button class="study-card card-${i}"><span>${c[0]}</span><h3>${c[1]}</h3><p>${c[2]}</p><i>→</i></button>`).join('')}</div><section class="panel recent"><div class="section-title"><h3>Recent study sets</h3><button>View all →</button></div><div class="recent-row"><b>Photosynthesis & cellular respiration</b><span>18 flashcards</span><button>Continue →</button></div></section></main>`; }
function library() { return `${header('Library', 'Everything you need for school, in one calm place.')}<main class="content library"><div class="library-top"><button class="primary">＋ Upload files</button><button class="outline">New folder</button><div class="search">⌕ Search your library</div></div><div class="file-tabs"><button class="active">All files</button><button>Notes</button><button>PDFs</button><button>Study guides</button><button>Projects</button></div><section class="folder-grid"><div class="folder"><span>▰</span><b>Biology</b><small>8 files</small></div><div class="folder"><span>▰</span><b>Algebra II</b><small>12 files</small></div><div class="folder"><span>▰</span><b>English</b><small>6 files</small></div></section><section class="panel file-list"><div class="section-title"><h3>Recently added</h3><button>Sort: Recent ⌄</button></div>${[['PDF','Cell Structure Notes','Biology · Yesterday'],['DOC','The Odyssey — draft','English · Sep 14'],['PDF','Quadratic Equations Review','Algebra II · Sep 12']].map(f=>`<article><span class="file-type">${f[0]}</span><div><b>${f[1]}</b><p>${f[2]}</p></div><button>•••</button></article>`).join('')}</section></main>`; }
function editor() { return `${header('Human editor', 'Thoughtful writing support that keeps your voice at the center.')}<main class="content editor"><section class="editor-banner"><span>✎</span><div><h2>Your words. <em>Clearer.</em></h2><p>Get copy-ready suggestions for grammar, clarity, vocabulary, and flow—without losing what makes your writing yours.</p></div></section><div class="editor-grid"><section class="writing"><div class="section-title"><h3>My draft</h3><span>0 words</span></div><textarea placeholder="Paste or start writing here…"></textarea><div><button class="outline">Import from library</button><button class="primary">Review my writing →</button></div></section><aside class="suggestions"><h3>Writing support</h3><p>Start a draft to receive gentle, specific suggestions.</p><ul><li>✓ Grammar & mechanics</li><li>✓ Clarity & flow</li><li>✓ Vocabulary choices</li><li>✓ Repetition & style</li></ul><small>Suggestions are designed to support your authentic voice—not replace it.</small></aside></div></main>`; }
function subjectsPage(){ return `${header('Customize subjects','Choose the learning spaces that belong in your sidebar.')}<main class="content"><div class="subject-settings">${subjects.map(([name,icon,color])=>`<button class="subject-pick${mark(name)}" data-subject="${name}"><span class="subject-icon ${color}">${icon}</span>${name}<b>✓</b></button>`).join('')}</div></main>`; }
function renderApp(){ document.querySelector('#app').innerHTML = `<div class="app-shell">${sidebar()}<div class="backdrop"></div><main class="main">${({school,chat,study,library,editor,images:library,subjects:subjectsPage})[page]()}</main></div>`; bind(); }
function bind(){ document.querySelectorAll('[data-page]').forEach(el=>el.onclick=()=>{page=el.dataset.page;mobileOpen=false;renderApp();}); document.querySelector('.menu')?.addEventListener('click',()=>{mobileOpen=true;renderApp();});document.querySelector('.close-mobile')?.addEventListener('click',()=>{mobileOpen=false;renderApp();}); document.querySelector('.backdrop')?.addEventListener('click',()=>{mobileOpen=false;renderApp();});document.querySelector('#motion')?.addEventListener('click',()=>document.body.classList.toggle('reduce-motion')); document.querySelectorAll('.subject-settings .subject-pick').forEach(el=>el.onclick=()=>{const n=el.dataset.subject;selectedSubjects=selectedSubjects.includes(n)?selectedSubjects.filter(x=>x!==n):[...selectedSubjects,n];localStorage.setItem('human-ai-subjects',JSON.stringify(selectedSubjects));renderApp();}); }
localStorage.getItem('human-ai-onboarded') ? renderApp() : renderOnboarding();
